# Generated by Django 6.0.4 on 2026-04-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryphoto",
            name="category",
            field=models.CharField(
                choices=[
                    ("events", "Events"),
                    ("meetings", "Meetings"),
                    ("orientation", "Orientation"),
                    ("general", "General"),
                ],
                default="general",
                max_length=30,
            ),
        ),
    ]
