# Generated by Django 6.0.4 on 2026-04-20 16:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token_created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
