# Generated by Django 6.0.4 on 2026-04-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_email_verification_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_token",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
