# Generated by Django 6.0.4 on 2026-04-24 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_password_reset_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_token_created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
