# Generated by Django 6.0.4 on 2026-04-26 09:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_verification_token_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingProfileUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("data_json", models.TextField(default="{}")),
                ("photo_path", models.CharField(blank=True, max_length=500)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_profile_update",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
