# Generated by Django 6.0.4 on 2026-04-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_pendingprofileupdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("second_admin", "2nd Admin"),
                    ("advisor", "Advisor"),
                    ("member", "Member"),
                ],
                default="member",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="PendingProfileUpdate",
        ),
    ]
