# Generated by Django 6.0.4 on 2026-04-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_role_delete_pendingprofileupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("", "Not specified"),
                ],
                default="",
                max_length=5,
            ),
        ),
    ]
