# Generated by Django 6.0.4 on 2026-04-30 19:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_profile_blood_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_approved",
            field=models.BooleanField(
                default=False,
                help_text="Admin must approve the account after email verification",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="account_rejected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="rejection_reason",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name="PendingProfileChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=500)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("new_bio", models.TextField(blank=True, null=True)),
                (
                    "new_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("new_batch", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "new_designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "new_blood_group",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "new_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pending/"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_profile_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_profile_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
