# Generated by Django 6.0.4 on 2026-04-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="email_audience",
            field=models.CharField(
                choices=[
                    ("all", "All Users"),
                    ("members", "Members Only"),
                    ("advisors", "Advisors Only"),
                    ("admins", "Admins Only"),
                ],
                default="all",
                max_length=20,
            ),
        ),
    ]
